# Generated by Django 3.1.7 on 2021-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_description', models.TextField(max_length=2000)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
