# Generated by Django 3.1.7 on 2021-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product cost '),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='product created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description',
            field=models.TextField(max_length=2000, verbose_name='product decription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=200, verbose_name='product name '),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product price'),
        ),
    ]
