# Generated by Django 3.1.7 on 2021-09-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catname', models.CharField(max_length=50, verbose_name='name')),
                ('Catdesc', models.TextField(verbose_name=' category description')),
                ('Catimg', models.ImageField(upload_to='category/')),
                ('Catparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
