# Generated by Django 3.1.7 on 2021-09-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Catparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'Catparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
