# Generated by Django 3.1.7 on 2021-09-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210902_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'ProductImge', 'verbose_name_plural': 'ProductImge'},
        ),
        migrations.CreateModel(
            name='ProductAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALAlternative', models.ManyToManyField(related_name='Alternative_products', to='product.Product')),
                ('PALproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product')),
            ],
            options={
                'verbose_name': 'ProductAlternative',
                'verbose_name_plural': 'ProductAlternatives',
            },
        ),
    ]
