# Generated by Django 3.1.7 on 2021-09-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210902_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccessores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAcAlternative', models.ManyToManyField(related_name='Accessory_products', to='product.Product')),
                ('PAcproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product')),
            ],
            options={
                'verbose_name': 'ProductAccessores',
                'verbose_name_plural': 'ProductAccessores',
            },
        ),
    ]
